# Generated by Django 4.1.7 on 2023-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_english', models.CharField(max_length=64)),
                ('in_ukrainian', models.CharField(max_length=64)),
            ],
        ),
    ]
