# Generated by Django 4.1.7 on 2023-02-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_words', '0002_levels_topics_words_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
