# Generated by Django 4.1.7 on 2023-03-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_words', '0003_alter_topics_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrregularVerbs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_form', models.CharField(max_length=64)),
                ('second_form', models.CharField(max_length=64)),
                ('third_form', models.CharField(max_length=64)),
                ('translate', models.CharField(max_length=64)),
            ],
        ),
    ]
