# Generated by Django 4.1.7 on 2023-03-09 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('english_words', '0005_userwords_usertests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertests',
            old_name='all_in_choice',
            new_name='all_test',
        ),
        migrations.RenameField(
            model_name='usertests',
            old_name='all_in_test',
            new_name='false_test',
        ),
        migrations.RenameField(
            model_name='usertests',
            old_name='false_in_choice',
            new_name='true_test',
        ),
        migrations.RemoveField(
            model_name='usertests',
            name='false_in_test',
        ),
        migrations.RemoveField(
            model_name='usertests',
            name='true_in_choice',
        ),
        migrations.RemoveField(
            model_name='usertests',
            name='true_in_test',
        ),
    ]
